version: "3.8"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434